version: 3

tasks:
  install:
     desc: Install dependencies
     cmds:
       - pip install twine
       - python setup.py install

  lint:
    desc: Lint code
    cmds:
      - pylint --rcfile=.pylintrc --reports=y --exit-zero journify | tee pylint.out

  test:
    desc: Test code
    cmds:
      - python -m unittest discover journify/test -v --pattern '*.py'

  release:
    desc: Release to PyPI
    cmds:
      - python setup.py sdist bdist_wheel
      - twine upload --skip-existing dist/* --non-interactive